# This is a basic workflow to help you get started with Actions

name: auto security scan using docker 

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up Python 3.7.13
      - name: Setup Python 3.7.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.13

      # Install python dependency
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-owasp-zap-v2.4

      - name: Start ZAP Docker
        run: |
          docker run -u zap -p 8090:8090 -d owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=12345 -addoninstall ascanrulesAlpha -addoninstall ascanrulesBeta -addoninstall network
          sleep 20
      
      # - name: Sleep for a bit to be docker up
      #   uses: jakejarvis/wait-action@master
      #   with:
      #     time: '20s'

      - name: Run Script to get ZAP Stats
        run: bash e2eTest.sh


      
